import terser from '@rollup/plugin-terser';
import dts from 'rollup-plugin-dts';

export default [
  // Main JavaScript bundle configuration
  {
    input: 'src/cosmicwave.js',
    output: [
      {
        file: 'dist/cosmicwave.js',
        format: 'umd',
        name: 'cosmicwave',
      },
      {
        file: 'dist/cosmicwave.min.js',
        format: 'umd',
        name: 'cosmicwave',
        plugins: [terser()],
      },
      {
        file: 'www/cosmicwave.min.js',
        format: 'umd',
        name: 'cosmicwave',
        plugins: [terser()],
      },
    ],
  },
  {
    input: 'src/cosmicpoly.js',
    output: [
      {
        file: 'dist/cosmicpoly.js',
        format: 'umd',
        name: 'cosmicpoly',
      },
      {
        file: 'dist/cosmicpoly.min.js',
        format: 'umd',
        name: 'cosmicpoly',
        plugins: [terser()],
      },
      {
        file: 'www/cosmicpoly.min.js',
        format: 'umd',
        name: 'cosmicpoly',
        plugins: [terser()],
      },
    ],
  },
  // Types bundle configuration
  {
    // Point this to the TEMPORARY folder generated by tsc
    input: './dist/types-temp/cosmicwave.d.ts',
    output: [
      {
        file: 'dist/cosmicwave.d.ts',
        format: 'es',
      },
    ],
    plugins: [dts()],
  },
  // Types bundle configuration for cosmicpoly
  {
    // Point this to the TEMPORARY folder generated by tsc
    input: './dist/types-temp/cosmicpoly.d.ts',
    output: [
      {
        file: 'dist/cosmicpoly.d.ts',
        format: 'es',
      },
    ],
    plugins: [dts()],
  },
];
